services:
  esidor.dto.resolver_storage:
    public: true
    class: Esidor\DtoBundle\Resolver\DtoResolversStorage

  Esidor\DtoBundle\Resolver\DtoArgumentValueResolver:
    arguments:
      $dtoResolversStorage: '@esidor.dto.resolver_storage'
    tags:
      - { name: controller.argument_value_resolver, priority: 50 }

  Esidor\DtoBundle\Resolver\DtoConstraintViolationListResolver:
    arguments:
      $dtoResolversStorage: '@esidor.dto.resolver_storage'
      $validator: '@validator'
    tags:
      - { name: controller.argument_value_resolver, priority: 51 }

